// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKynLJZ3JPiZrfDhq2xy4IfnUMWBZZWPM',
    appId: '1:912469034938:web:5ea387ebda52b9569fff83',
    messagingSenderId: '912469034938',
    projectId: 'semproject-f02aa',
    authDomain: 'semproject-f02aa.firebaseapp.com',
    storageBucket: 'semproject-f02aa.appspot.com',
    measurementId: 'G-3MLQY2FGY4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ_9PFvgyZ6QSMLLoNFDJUScu6DneoVKs',
    appId: '1:912469034938:ios:60a6e06b5031dc8a9fff83',
    messagingSenderId: '912469034938',
    projectId: 'semproject-f02aa',
    storageBucket: 'semproject-f02aa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ_9PFvgyZ6QSMLLoNFDJUScu6DneoVKs',
    appId: '1:912469034938:ios:60a6e06b5031dc8a9fff83',
    messagingSenderId: '912469034938',
    projectId: 'semproject-f02aa',
    storageBucket: 'semproject-f02aa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKynLJZ3JPiZrfDhq2xy4IfnUMWBZZWPM',
    appId: '1:912469034938:web:56b5ffc499855f319fff83',
    messagingSenderId: '912469034938',
    projectId: 'semproject-f02aa',
    authDomain: 'semproject-f02aa.firebaseapp.com',
    storageBucket: 'semproject-f02aa.appspot.com',
    measurementId: 'G-QR8WXNKB8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY_bTopx9db2gPdmKzI_6tzvzTiu0iZcE',
    appId: '1:912469034938:android:8d60e32f4a12060a9fff83',
    messagingSenderId: '912469034938',
    projectId: 'semproject-f02aa',
    storageBucket: 'semproject-f02aa.appspot.com',
  );

}